name: Build + Deploy docs
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'overrides/**'
      - '.github/workflows/**'
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'overrides/**'
      - '.github/workflows/**'
jobs:
  main:
    name: Build + Deploy
    runs-on: ubuntu-latest
    steps:
      # checkout this repo
      - name: Checkout repo # Name of the step
        uses: actions/checkout@v4 # Action to run
      - name: Set up Python # Name of the step
        uses: actions/setup-python@v5 # Action to run
        with: # Inputs for the action
          python-version: 3.9 # Version of Python to use
      - name: Install dependencies # Name of the step
        run: | # Command to run
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            python -m mkdocs build
      - name: Configure AWS Creadentials
        uses: aws-actions/configure-aws-credentials@v4
        env:
          S3_PATH: "s3://carlos-grande-me"
        with:
          aws-region: eu-west-3
          aws-access-key-id: ${{ secrets.S3_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_SECRET_KEY }}
      - name: Syncronize files with S3 bucket # Name of the step
        run: | # Command to run
            aws s3 sync site/ s3://${{ secrets.S3_BUCKET_NAME }}
